pipelines:
    default:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/pinakapos/repoflutterpinakapos/src.git 
            ##- cd repoflutterpinakapos.git ## cd followed by your Github repository Name
            - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE"@https://github.com/raghu-Alekya/Pinaka-Pos.git
            
            